kind: pipeline
name: GNU GCC ARM NON ELF BUILD

clone:
  disable: true

steps:
- name: arm-linux-gnueabi
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel git curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm -s gnu -v 11 -V -p zstd -tm" /drone/src/build-gnu-gcc-tc.log

---
kind: pipeline
name: GNU GCC ARM BARE METAL / ELF

clone:
  disable: true

steps:
- name: arm-eabi
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel git curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm --elf -s gnu -v 11 -V -p zstd -tm" /drone/src/build-gnu-gcc-tc.log

---
kind: pipeline
name: GNU GCC ARM64 NON ELF BUILD

clone:
  disable: true

steps:
- name: aarch64-linux-gnu
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel git curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm64 -s gnu -v 11 -V -p zstd -tm" /drone/src/build-gnu-gcc-tc.log

---
kind: pipeline
name: GNU GCC ARM64 BARE METAL / ELF

clone:
  disable: true

steps:
- name: aarch64_elf
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel git curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm64 --elf -s gnu -v 11 -V -p zstd -tm" /drone/src/build-gnu-gcc-tc.log